---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - manila.example.com
  resources:
  - formats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manila.example.com
  resources:
  - formats/finalizers
  verbs:
  - update
- apiGroups:
  - manila.example.com
  resources:
  - formats/status
  verbs:
  - get
  - patch
  - update
